[tool.poetry]
name = "wandbot"
version = "0.1.0"
description = "A Q&A bot for Weights & Biases documnetation"
authors = ["parambharat <bharat.ramanathan@wandb.com>"]
license = "LICENSE"
readme = "README.md"
homepage = "https://github.com/wandb/wandbot"
repository = "https://github.com/wandb/wandbot"
include = ["src/**/*", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.24.2"
wandb = "^0.15.0"
langchain = { version = "^0.0.190", optional = true }
openai = { version = "^0.27.6", optional = true }
tiktoken = { version = "^0.4.0", optional = true }
pandas = { version = "^2.0.1", optional = true }
unstructured = { version = "^0.7.1", optional = true }
urllib3 = { version = "*", optional = true }
slack-bolt = { version = "^1.16.1", optional = true }
slack-sdk = { version = "^3.12.0", optional = true }
discord = { version = "^2.2.3", optional = true }
fastapi = { extras = ["all"], version = "^0.96.0", optional = true }
uvicorn = { version = "^0.22.0", optional = true }
python-dotenv = "^1.0.0"
llama-index = { version = "^0.6.19", optional = true }
giturlparse = { version = "^0.10.0", optional = true }
fuzzywuzzy = { version = "^0.18.0", optional = true }
chromadb = {version = "^0.3.25", optional=true }
scipy = { version = "^1.10.1", optional = true }
scikit-learn = { version = "^1.2.2", optional = true }
tabulate = "^0.9.0"

[tool.poetry.extras]
slack = ["slack-bolt", "slack-sdk"]
replit = ["replit", "Flask", "urllib3"]
discord = ["discord"]
chat = ["scikit-learn", "scipy", "chromadb", "llama-index", "giturlparse", "unstructured", "pandas", "tiktoken", "openai", "langchain",]
api = ["fastapi", "uvicorn", ]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"