[tool.poetry]
name = "wandbot"
version = "0.1.0"
description = "A Q&A bot for Weights & Biases documnetation"
authors = ["parambharat <bharat.ramanathan@wandb.com>"]
license = "LICENSE"
readme = "README.md"
homepage = "https://github.com/wandb/wandbot"
repository = "https://github.com/wandb/wandbot"
include = ["src/**/*", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.24.2"
wandb = "^0.15.0"
langchain = { version = "^0.0.142", optional = true }
openai = { version = "^0.27.2", optional = true }
tiktoken = { version = "^0.3.3", optional = true }
pandas = { version = "^2.0.1", optional = true }
unstructured = { version = "^0.6.2", optional = true }
replit = { version = "^3.2.4", optional = true }
Flask = { version = "^2.2.0", optional = true }
urllib3 = { version = "^1.26.12", optional = true }
slack-bolt = { version = "^1.16.1", optional = true }
slack-sdk = { version = "^3.12.0", optional = true }
discord = { version = "^2.2.2", optional = true }
fastapi = { extras = ["all"], version = "^0.95.0", optional = true }
uvicorn = { version = "^0.21.1", optional = true }
python-dotenv = "^1.0.0"
llama-index = { version = "^0.5.23", optional = true }
giturlparse = { version = "^0.10.0", optional = true }
fuzzywuzzy = { version = "^0.18.0", optional = true }
chromadb = { git = "https://github.com/parambharat/chroma.git", rev = "no-sentence-transformers" }
scipy = { version = "^1.10.1", optional = true }
scikit-learn = { version = "^1.2.2", optional = true }

[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = { extras = ["yapf", "rope", "pyflakes"], version = "^1.5.9" }

[tool.poetry.extras]
slack = ["slack-bolt", "slack-sdk"]
replit = ["replit", "Flask", "urllib3"]
discord = ["discord"]
chat = ["scikit-learn", "scipy", "chromadb", "llama-index", "giturlparse", "unstructured", "pandas", "tiktoken", "openai", "langchain", ]
api = ["fastapi", "uvicorn", ]

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"