[tool.poetry]
name = "wandbot"
version = "1.0.0"
description = "A Q&A bot for Weights & Biases documentation"
authors = ["parambharat <bharat.ramanathan@wandb.com>"]
license = "LICENSE"
readme = "README.md"
homepage = "https://github.com/wandb/wandbot"
repository = "https://github.com/wandb/wandbot"
include = ["src/**/*", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.25.2"
wandb = "^0.15.12"
openai = "^0.28.1"
tiktoken = "^0.5.1"
pandas = "^2.0.3"
unstructured = "^0.10.5"
pydantic-settings = "^2.0.3"
gitpython = "^3.1.32"
giturlparse = "^0.12.0"
scikit-learn = "^1.3.0"
python-dotenv = "^1.0.0"
faiss-cpu = "^1.7.4"
slack-bolt = "^1.18.0"
slack-sdk = "^3.21.3"
discord = "^2.3.2"
markdown = "^3.4.4"
fastapi = "^0.103.1"
langdetect = "^1.0.9"
llama-index = "^0.8.36"
tree-sitter-languages = "^1.7.0"
cohere = "^4.27"
markdownify = "^0.11.6"
uvicorn = "^0.23.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"
line_length = 119
skip = [".gitignore", "data", "examples", "notebooks", "artifacts", ".vscode", ".github", ".idea", ".replit", "*.md", "wandb", ".env", ".git", ]

[tool.black]
line-length = 119
skip = [".gitignore", "data", "examples", "notebooks", "artifacts", ".vscode", ".github", ".idea", ".replit", "*.md", "wandb", ".env", ".git", ]
