[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["parambharat <bharat.ramanathan@wandb.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.22.2"
replit = "^3.2.4"
Flask = "^2.2.0"
urllib3 = "^1.26.12"
slack-bolt = "^1.16.1"
slack-sdk = "^3.12.0"
wandb = "^0.14.0"
langchain = "^0.0.123"
faiss-gpu = "^1.7.2"
openai = "^0.27.2"
tiktoken = "^0.3.0"
pandas = "^1.5.3"
unstructured = "^0.5.7"


[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = {extras = ["yapf", "rope", "pyflakes"], version = "^1.5.9"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"